name: Mac Clara Test

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build-and-testing:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Eigen
        run: brew install eigen

      - name: Build and test
        run: |
          cd clara_test
          chmod +x run_test
          ./run_test
