name: Unit Testing

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build-and-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Eigen
        run: sudo apt-get install libeigen3-dev

      - name: Build and test
        run: |
          cd clara_test/run_test
          chmod +x run_test
          ./run_test
